name: publish-docker-image

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-push-stable-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: aykhans
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: aykhans/bsky-pdsadmin
                  tags: |
                      type=ref,event=tag
                      type=raw,value=latest
                      type=raw,value=stable

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
